server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: musinsa
      password: musinsapassword
      maximum-pool-size: 10
      jdbc-url: jdbc:h2:mem:commerce;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-musinsa
  jpa:
    database: h2
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
      mode: always


